name: Greetings

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]
    paths:
      - 'force-app/**'
  workflow_dispatch:

jobs:
  deploy-to-sit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
