name: Greetings

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master, RLB ]
    paths:
      - 'force-app/**'
  workflow_dispatch:

jobs:
  deploy-to-sit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "🔎 The full name is ${{ github.event.pull_request.head.repo.full_name }} and your repository is ${{ github.repository }}."
      - name: Update Repo
        run: sudo apt-get update
      - name: 'Installing java'
        run: sudo apt-get install openjdk-8-jdk 
