name: Greetings

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]
    paths:
      - 'force-app/**'
  workflow_dispatch:

jobs:
  deploy-to-sit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
