# Unique name for this workflow
name: Validate PR on SIT branch

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ sit ]
    paths:
      - 'force-app/**'
  workflow_dispatch:

jobs:
  call-salesforce-deploy-actions-wf:
    uses: ./.github/workflows/salesforce-deploy-actions.yml
    with:
      DEPLOY_TYPE: CHECK-ONLY
      DEPLOY_ORG: SIT
    secrets:
      SALESFORCE_DEVHUB_USERNAME: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
      SALESFORCE_CONSUMER_KEY: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
      SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}