name: PR validate SIT branch

on:
  workflow_dispatch:

jobs:
  call-sfdx-deploy-actions:
    uses: ./.github/workflows/sfdx-deploy-actions.yml
  authorize-salesforce-org:
    - name: 'Populat key'
      shell: bash
      run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
    
    - name: Setup AUth
      run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --setdefaultdevhubusername
  deploy-salesforce-org:
    - name: 'Check-only deploy delta changes - run specified tests'
      if: ${{ env.APEX_TESTS != 'all' }}
      run: |
          echo ${{env.APEX_TESTS}}             
          sfdx force:source:deploy -x package/package.xml --checkonly --testlevel RunSpecifiedTests --runtests ${{env.APEX_TESTS}} -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --json
      # If the env variable equals all, we run all tests
    - name: 'Check-only deploy delta changes - run all tests'
      if: ${{ env.APEX_TESTS == 'all' }}
      run: |
          sfdx force:source:deploy -x package/package.xml --checkonly --testlevel RunLocalTests -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --json  